nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']
        # allow_origin: ['%env(CORS_ALLOW_ORIGIN)%','http://localhost:4200',]
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        # allow_headers: ['Content-Type', 'Authorization']
        # expose_headers: ['Link']
        allow_headers: ['Content-Type', 'Authorization,', 'X-Requested-With', 'Accept', 'Origin']
        expose_headers: ['Link','Content-Type']
        max_age: 3600
    paths:
        # '^/': null
        '^/api/': ~





